version: "3.1"

services:

  db:
    container_name: db
    build: /src/main/resources/db
    restart: always
    networks:
      - db-network
    env_file:
      - .env
    ports:
      - "3306:3306"

  keu-server:
    container_name: keu-server
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    env_file:
      - .env
    ports:
      - "8080:8080"
    networks:
      - db-network
    depends_on:
      - db

networks:
  db-network: